### ISSUE TITLE
network install problem

### ISSUE THREAD

**Issue by lowburger** [rashevskyv/dbi#19]
Hi I try network install with dbi but I face issue. I start python http server, then I use ApacheHTTP|Network repo|http://ip:port/ file on dbi. dbi connect to my folder right away and I see all my files and I can choose any file but when I reach final "Install options" screen dbi says file is 0B and says "Nothing to install" at bottom of screen. I checked on other device this server and I can download the file, dbi has problem with python 3 http server?

**Comment by duckbill007** [comment]
Just tried run "python -m SimpleHTTPServer 7800"  

Works just fine with DBI

**Comment by lowburger** [comment]
> Just tried run "python -m SimpleHTTPServer 7800"
> 
> Works just fine with DBI

Here just doesn't work, always nothing to install error in final screen. I don't understand it because dbi see the files but can't do the install. I check python console, there some errors and says connection closed.

**Comment by lowburger** [comment]
Hi, I brought here my python console error. Maybe you can tell DBI problem or my problem? Using command: python -m http.server

```
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
192.168.0.3 - - [22/Mar/2021 16:06:36] "GET /%23Breakforcist%20Battle/ HTTP/1.1" 200 -
192.168.0.3 - - [22/Mar/2021 16:06:39] "GET / HTTP/1.1" 200 -
192.168.0.3 - - [22/Mar/2021 16:06:51] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.3', 19072)
Traceback (most recent call last):
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 415, in handle_one_request
    method()
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 654, in do_GET
    self.copyfile(f, self.wfile)
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 853, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "C:\Users\Mainc\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
```

**Comment by duckbill007** [comment]
Just tested with python 2.7.6 on Linux. Works fine.
