### ISSUE TITLE
Latest DBIBackend Compiled to exe

### ISSUE THREAD

**Issue by x7l7j8cc** [rashevskyv/dbi#289]
Latest version compiled to exe.
Hope it's appreciated. ;)

... [Check here](https://github.com/rashevskyv/dbi/issues/289#issuecomment-1781574499)

from latest release:
> dbibackend.exe is an old version, cause I have problems with building new version to exe file. Will try to fix it later. If anyone can built it, will be appreciated.

**Comment by rashevskyv** [comment]
Thanx!!

**Comment by rashevskyv** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "dbibackend.py", line 175, in start_server
  File "dbibackend.py", line 152, in connect_to_switch
  File "usb\core.py", line 1309, in find
usb.core.NoBackendError: No backend available

Old one works fine

**Comment by x7l7j8cc** [comment]
Please, try this new one... To me now works..

[dbibackend.zip](https://github.com/rashevskyv/dbi/files/13180994/dbibackend.zip)

**Comment by rashevskyv** [comment]
Works fine now! Thanks! Will add to latest release
