### ISSUE TITLE
DBIbackend NotImplementedError

### ISSUE THREAD

**Issue by observeroftime01** [rashevskyv/dbi#291]
Using DBI 628, HOS 16.1.0, Atmosphere 1.5.5

Steps to reproduce:
1. Start DBI backend on a Win10x64 machine
2. Add some files (or folders) containing nsp files
3. Start the server
4. On the switch, open DBI via HBmenu
5. Select "install title from DBIbackend"
6. Connect your switch to your PC using a USB-C cable
7. the following error appears in the windows console

```
Exception in thread Thread-1 (start_server):
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "threading.py", line 989, in run
  File "dbibackend.py", line 175, in start_server
  File "dbibackend.py", line 158, in connect_to_switch
  File "usb\core.py", line 959, in reset
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 131, in managed_open
  File "usb\backend\libusb1.py", line 804, in open_device
  File "usb\backend\libusb1.py", line 652, in __init__
  File "usb\backend\libusb1.py", line 600, in _check
NotImplementedError: Operation not supported or unimplemented on this platform
```
8. No connection is established. 

If further information is required I'd be happy to assist. Am I simply doing this wrong? I have never used DBIbackend before until today, so I am not sure if I am even going about this the right way. Thank you for your time and consideration.

**Comment by TomySakazaki** [comment]
Follow instructions on https://github.com/rashevskyv/dbi/blob/main/README_ENG.md#install-title-from-dbibackend
You are missing the libusbK drivers. Install them using zadig.

**Comment by duckyb** [comment]
![image](https://github.com/rashevskyv/dbi/assets/27895007/03e1f308-f501-4e09-bbf9-2e714c103556)

I had the same issue and the above solution worked for me. Thanks. 👍🏻 
(I had the drivers initially but I forgot to reinstall them after formatting my machine)
